[package]
name = "record-tools-rs"
version = "0.1.0"
authors = [
    "Christoph Kappel <christoph@unexist.dev>"
    ]
license-file = "LICENSE"
homepage = "https://unexist.dev"
repository = "https://hg.unexist.dev/record-tools-rs"
edition = "2024"
exclude = ["/Taskfile.yml"]

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
