doc_type = "adoc"
template_dir = "./templates"

[[doc_types]]
name = "adoc"
link_format = "link:${LINK}[${TITLE}]"

[[doc_types]]
name = "md"
link_format = "[${TITLE}](${LINK})"

[[record_types]]
name = "adr"
directory = "./records/adrs"
template_name = "adr-template"

[[record_types]]
name = "tdr"
directory = "./records/tdrs"
template_name = "tdr-template"
