file_type = "adoc"
template_dir = "./templates"
adr_dir = "./architecture-decision-record"
tdr_dir = "./technical-debt-records"

[[formats]]
name = "adr"
directory = "./architecture-decision-record"
field_regex = "NAME:[.]*| VALUE"

[[formats]]
name = "tdr"
directory = "./technical-debt-records"
field_regex = "NAME:[.]*| VALUE"
