file_type = "adoc"
template_dir = "./templates"

[[record_type]]
name = "adr"
directory = "./records/adrs"
default_template_name = "adr-template"

[[record_type]]
name = "tdr"
directory = "./records/tdrs"
default_template_name = "tdr-template"
